### ISSUE TITLE
Confusing validation result

### ISSUE THREAD

**Issue by reuteran** [rtrlib/python-binding#11]
Lets say I have these two ROAs:

```
AS65601 192.168.0.0/16 - 24
AS65600 192.168.0.0/22 - 22
```

and I validate 192.168.0.0/24 with origin AS 65600:
```
>>> result = mgr.validate(65600, '192.168.0.0', 24)
>>> result.is_invalid
True
>>> result.is_valid
False
```
This is correct, but If I look at the reasons for invalidity:
```
>>> result.as_invalid
True
>>> result.as_valid
True
>>> result.length_invalid
True
>>> result.length_valid
True
```

I assume 'as_invalid' is True when the validation result is invalid and there exists a ROA with a different ASN than the one being validated. 'as_valid' is True because there is also a ROA with the correct ASN, but wrong length. Same goes for length_valid, length_invalid.

While this isn't a bug, its still a bit confusing. I think we should change the validation result so it contains the actual matching ROAs and for each individual ROA the reasons why this ROA does not match (wrong AS, wrong length, wrong both).

**Comment by mroethke** [comment]
That information is already there and accessible. The `reason` member of the `ValidationResult` class contains a list of all ROAs returned by rtrlibs `pfx_table_validate_r` function.

So removing the {length,as}_{in,}valid properties would suffice wouldn't it?

**Comment by reuteran** [comment]
I think removing result.as_valid and result.length_valid would be enough, or is that what you mean?
