### ISSUE TITLE
Expected location of  librtr.so.0

### ISSUE THREAD

**Issue by vkotronis** [rtrlib/python-binding#12]
Hello, I have installed rtrlib and all dependencies, and then the python-binding. During Make for rtrlib I also did "install" to copy everything to system folders; librtr.so.0 is present at /usr/local/lib64/librtr.so
However, when I try to import the Python wrapper:
```
>>> import rtrlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/rtrlib-0.1-py3.6-linux-x86_64.egg/rtrlib/__init__.py", line 12, in <module>
    from .rtr_manager import RTRManager, PfxvState
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/rtrlib-0.1-py3.6-linux-x86_64.egg/rtrlib/rtr_manager.py", line 17, in <module>
    from _rtrlib import ffi, lib
ImportError: Error loading shared library librtr.so.0: No such file or directory (needed by /usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/rtrlib-0.1-py3.6-linux-x86_64.egg/_rtrlib.abi3.so)
```

Any ideas? What is the default location where the wrapper expects the .so to be present?

**Comment by vkotronis** [comment]
As a temporary fix, for now I solved it as follows:
```
bash-4.4# ln -s /usr/local/lib64/librtr.so /usr/local/lib/librtr.so
bash-4.4# ln -s /usr/local/lib64/librtr.so.0 /usr/local/lib/librtr.so.0
bash-4.4# ln -s /usr/local/lib64/librtr.so.0.7.0 /usr/local/lib/librtr.so.0.7.0
```

**Comment by mroethke** [comment]
The binding does not have any expectations about the location of rtrlib, it relies on the dynamic linker for finding and loading it. You should probably configure the install prefix for rtrlib (just add `-D CMAKE_INSTALL_PREFIX=/usr/local/lib/` to the cmake call if that is what you want). You could also set the env var `LD_LIBRARY_PATH` to include `/usr/local/lib64`.
