### ISSUE TITLE
Print current status of prefix-table

### ISSUE THREAD

**Issue by salsh** [rtrlib/python-binding#4]
Is there a possibility to print prefix-table entries all at once instead of calling the update-callback function from the RTRManager? 
Is it currently possible to call the RTRLib-provided functions: pfx_table_for_each_ipv4_record and pfx_table_for_each_ipv6_record?

**Comment by mroethke** [comment]
Yes, but currently you have to deal with cffi yourself.

You can call every function provided by rtrlib from the _rtrlib.lib module, _rtrlib is the ffi object containing the actual bindings to the c functions.

**Comment by waehlisch** [comment]
@mroethke it's nice temporary solution. Can you also extend the Python binding to support this interface natively?

**Comment by mroethke** [comment]
Certainly, not before next month though.

**Comment by waehlisch** [comment]
@mroethke can you estimate when you have time for this issue?

**Comment by mroethke** [comment]
next week, same for #7

**Comment by mroethke** [comment]
Implemented with 4fd5194ce12e953448b286b78af080bfe2d919b5 usage example can be found [here](https://python-rtrlib.readthedocs.io/en/latest/usage.html#pfx-table-iteration-with-iterator)
