### ISSUE TITLE
Doc: Add cffi example

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/python-binding#6]
Would be good to have an example documented that explains usage of cffi and RTRlib.

**Comment by mroethke** [comment]
Something like [this](https://python-rtrlib.readthedocs.io/en/latest/usage.html#advanced-usage)?

**Comment by waehlisch** [comment]
Ping @salsh.

**Comment by salsh** [comment]
@mroethke: Thank you for the well documented example - works like a charm!

**Comment by smlng** [comment]
sounds like this is resolved, closing!
