### ISSUE TITLE
Memory Error: SIGPIPE

### ISSUE THREAD

**Issue by salsh** [rtrlib/python-binding#8]
I'm currently using the Python Binding to get ROA data from RPKI cache servers. Unfortunately I get an infrequent memory error SIGPIPE (after hours/days) which leads to an abort. I think the error is thrown by the RTRLib if a socket is not available anymore.

Is there a chance that the Python Binding catches the SIGPIPE error and reconnect the socket without killing the whole process?

PS: It seems that the BIRD client of the RTRLib had the same issue: https://github.com/rtrlib/bird-rtrlib-cli/commit/01f4d112236fcdb8bd2ad71dac8f9c626f7d1d26

**Comment by mroethke** [comment]
Sockets are handled by rtrlib itself, the binding has no business there. So if this really is a problem on the socket level rtrlib should handle it.

Could you provide more details about what you are doing and how you are doing it?
Stacktraces and/or some code would be nice too.


in the meantime you could try ignoring the signal with something like this.
```python
import signal
signal.signal(signal.SIG_IGN, signal.SIGPIPE)
```

**Comment by salsh** [comment]
I am using the binding to dump periodically ROA data from different cache servers via RTRLib. The source code is online: https://github.com/salsh/bgpstream-live-rpki-validation-crawler/blob/master/rtr_sync.py#L71

Basically I only initialize a RTRManager and if it is synced with the cache server the current prefix table will be dumped. I already tried the workaround unfortunately without success.

![traceback2](https://cloud.githubusercontent.com/assets/7374276/26309412/34135232-3efd-11e7-86b3-314173f81e1c.png)

**Comment by mroethke** [comment]
Sorry for the late response.

I wrote a little patch for rtrlib that might solve this, could you please try it?
You can find in in my rtrlib fork in the send_nosigpipe branch. Please build in debug mode.

If this still does not solve the problem I'll need more information about your system. Like exact os with version. I'd also like to know what type of internet connection you are running your script on.

**Comment by salsh** [comment]
Sorry for the late response as well! I tried the patch but it does not solve the problem. It seems to be a problem with the OS. I'm running the same code on Ubuntu 16.04 (even without the patch) and it works like a charm for days.

**OS:**
```
$ uname -a
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```
I don't have any general information about the Internet connection (computer of the university).

**Comment by smlng** [comment]
likely obsolete, also this issue is unrelated to the python binding
